INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
	VALUES('barbie','doll',80,55,18);
INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
	VALUES('Lego','Jurassic World',110,95,60);
INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
    VALUES('Lego','Star Wars',150,55,28);
INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
    VALUES('Hot Wheels','Monster Truck',80,55,18);
INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
    VALUES('Barbie','Barbie Dreamhouse',80,25,88);


INSERT INTO GAMES(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
	VALUES('Warhammer','Tempest of Souls',100,50,100);
INSERT INTO GAMES(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
	VALUES('Starling Games','A War of Whisperer',120,35,59);
INSERT INTO GAMES(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
    VALUES('Cephalofair Games','Gloomhaven Jaws of the Lion',120,35,62);
