INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
	VALUES('Barbie','doll',80,55,18);
INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
	VALUES('Lego','Jurassic World',110,95,60);
INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
    VALUES('Lego','Star Wars',150,55,28);
INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
    VALUES('Hot Wheels','Monster Truck',80,55,18);
INSERT INTO TOYS(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
    VALUES('Barbie','Barbie Dreamhouse',80,25,88);


INSERT INTO GAMES(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
	VALUES('Warhammer','Tempest of Souls',100,50,100);
INSERT INTO GAMES(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
	VALUES('Starling Games','A War of Whisperer',120,35,59);
INSERT INTO GAMES(BRAND, NAME, QTYSTART, QTYSOLD, UNITPRICE)
    VALUES('Cephalofair Games','Gloomhaven Jaws of the Lion',120,35,62);

INSERT INTO USERS(LOGIN, PASSWORD)
VALUES('abc@gmail.com', 'password');
INSERT INTO USERS(LOGIN, PASSWORD)
VALUES('kate@gmail.com', 'password1');
INSERT INTO USERS(LOGIN, PASSWORD)
VALUES('andy@gmail.com', 'password2');
INSERT INTO USERS(LOGIN, PASSWORD)
VALUES('danilo@gmail.com', 'password3');
INSERT INTO USERS(LOGIN, PASSWORD)
VALUES('aakash@gmail.com', 'password4');
INSERT INTO USERS(LOGIN, PASSWORD)
VALUES('reza@gmail.com', 'password5');